# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/patricia/Área de Trabalho/tela.ui'
#
# Created: Sat Jun 19 20:46:11 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PyQt4.QtGui import QHeaderView

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(625, 676)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listaProducoes = QtGui.QListWidget(self.centralwidget)
        self.listaProducoes.setGeometry(QtCore.QRect(10, 70, 321, 151))
        self.listaProducoes.setObjectName("listaProducoes")
        self.listaSentencas = QtGui.QListWidget(self.centralwidget)
        self.listaSentencas.setGeometry(QtCore.QRect(338, 47, 271, 201))
        self.listaSentencas.setObjectName("listaSentencas")
        self.botaoAdicionarProducao = QtGui.QPushButton(self.centralwidget)
        self.botaoAdicionarProducao.setGeometry(QtCore.QRect(230, 37, 85, 27))
        self.botaoAdicionarProducao.setObjectName("botaoAdicionarProducao")
        self.botaoGerarSentencas = QtGui.QPushButton(self.centralwidget)
        self.botaoGerarSentencas.setGeometry(QtCore.QRect(523, 13, 85, 27))
        self.botaoGerarSentencas.setObjectName("botaoGerarSentencas")
        self.caixaProducoes = QtGui.QLineEdit(self.centralwidget)
        self.caixaProducoes.setGeometry(QtCore.QRect(10, 40, 211, 23))
        self.caixaProducoes.setObjectName("caixaProducoes")
        self.caixaTamanhoProducoes = QtGui.QLineEdit(self.centralwidget)
        self.caixaTamanhoProducoes.setGeometry(QtCore.QRect(478, 17, 41, 23))
        self.caixaTamanhoProducoes.setObjectName("caixaTamanhoProducoes")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 20, 151, 20))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(13, 20, 311, 16))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.botaoConverterGRparaAF = QtGui.QPushButton(self.centralwidget)
        self.botaoConverterGRparaAF.setGeometry(QtCore.QRect(10, 222, 161, 27))
        self.botaoConverterGRparaAF.setObjectName("botaoConverterGRparaAF")
        self.tabelaTransicoes = QtGui.QTableWidget(self.centralwidget)
        self.tabelaTransicoes.setGeometry(QtCore.QRect(10, 310, 321, 241))
        self.tabelaTransicoes.setObjectName("tabelaTransicoes")
        self.tabelaTransicoes.verticalHeader().setResizeMode(QHeaderView.ResizeToContents)
        self.tabelaTransicoes.setColumnCount(0)
        self.tabelaTransicoes.setRowCount(0)
        self.botaoMinimizar = QtGui.QPushButton(self.centralwidget)
        self.botaoMinimizar.setGeometry(QtCore.QRect(11, 561, 160, 27))
        self.botaoMinimizar.setObjectName("botaoMinimizar")
        self.botaoDeterminizar = QtGui.QPushButton(self.centralwidget)
        self.botaoDeterminizar.setGeometry(QtCore.QRect(170, 561, 160, 27))
        self.botaoDeterminizar.setObjectName("botaoDeterminizar")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(340, 290, 281, 361))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"     \n"
"     border: 2px solid gray;\n"
"     border-radius: 5px;\n"
"     margin-top: 1ex; /* leave space at the top for the title */\n"
" }\n"
"QGroupBox::indicator:unchecked {\n"
"     image: url(:/images/checkbox_unchecked.png);\n"
" }\n"
"\n"
" QGroupBox::title {\n"
"     subcontrol-origin: margin;\n"
"     subcontrol-position: top center; /* position at the top center */\n"
"     padding: 0 3px;\n"
" }")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 96, 251, 16))
        self.label_7.setObjectName("label_7")
        self.caixaAlfabeto = QtGui.QLineEdit(self.groupBox_2)
        self.caixaAlfabeto.setGeometry(QtCore.QRect(10, 118, 113, 23))
        self.caixaAlfabeto.setMaxLength(1)
        self.caixaAlfabeto.setObjectName("caixaAlfabeto")
        self.botaoAdicionarAlfabeto = QtGui.QPushButton(self.groupBox_2)
        self.botaoAdicionarAlfabeto.setGeometry(QtCore.QRect(130, 116, 140, 27))
        self.botaoAdicionarAlfabeto.setObjectName("botaoAdicionarAlfabeto")
        self.botaoAdicionarEstado = QtGui.QPushButton(self.groupBox_2)
        self.botaoAdicionarEstado.setGeometry(QtCore.QRect(130, 40, 140, 27))
        self.botaoAdicionarEstado.setObjectName("botaoAdicionarEstado")
        self.caixaEstado = QtGui.QLineEdit(self.groupBox_2)
        self.caixaEstado.setGeometry(QtCore.QRect(10, 43, 113, 23))
        self.caixaEstado.setMaxLength(1)
        self.caixaEstado.setObjectName("caixaEstado")
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 241, 20))
        self.label_6.setObjectName("label_6")
        self.listaEstados = QtGui.QComboBox(self.groupBox_2)
        self.listaEstados.setGeometry(QtCore.QRect(10, 169, 111, 25))
        self.listaEstados.setObjectName("listaEstados")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 152, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 53, 15))
        self.label_4.setObjectName("label_4")
        self.listaAlfabeto = QtGui.QComboBox(self.groupBox_2)
        self.listaAlfabeto.setGeometry(QtCore.QRect(10, 215, 111, 25))
        self.listaAlfabeto.setObjectName("listaAlfabeto")
        self.botaoDeletarEstado = QtGui.QPushButton(self.groupBox_2)
        self.botaoDeletarEstado.setGeometry(QtCore.QRect(130, 169, 140, 27))
        self.botaoDeletarEstado.setObjectName("botaoDeletarEstado")
        self.botaoDeletarAlfabeto = QtGui.QPushButton(self.groupBox_2)
        self.botaoDeletarAlfabeto.setGeometry(QtCore.QRect(130, 215, 140, 27))
        self.botaoDeletarAlfabeto.setObjectName("botaoDeletarAlfabeto")
        self.cbFinal = QtGui.QCheckBox(self.groupBox_2)
        self.cbFinal.setGeometry(QtCore.QRect(130, 70, 101, 20))
        self.cbFinal.setObjectName("cbFinal")
        self.cbInicial = QtGui.QCheckBox(self.groupBox_2)
        self.cbInicial.setGeometry(QtCore.QRect(10, 70, 111, 20))
        self.cbInicial.setObjectName("cbInicial")
        self.botaoReconhecerSentenca = QtGui.QPushButton(self.groupBox_2)
        self.botaoReconhecerSentenca.setGeometry(QtCore.QRect(131, 328, 140, 27))
        self.botaoReconhecerSentenca.setObjectName("botaoReconhecerSentenca")
        self.caixaSentenca = QtGui.QLineEdit(self.groupBox_2)
        self.caixaSentenca.setGeometry(QtCore.QRect(10, 329, 111, 23))
        self.caixaSentenca.setObjectName("caixaSentenca")
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(12, 309, 261, 16))
        self.label_8.setObjectName("label_8")
        self.line_2 = QtGui.QFrame(self.groupBox_2)
        self.line_2.setGeometry(QtCore.QRect(17, 142, 251, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.caixaER = QtGui.QLineEdit(self.groupBox_2)
        self.caixaER.setGeometry(QtCore.QRect(10, 274, 111, 23))
        self.caixaER.setObjectName("caixaER")
        self.botaoConverterERparaAF = QtGui.QPushButton(self.groupBox_2)
        self.botaoConverterERparaAF.setGeometry(QtCore.QRect(130, 272, 141, 27))
        self.botaoConverterERparaAF.setObjectName("botaoConverterERparaAF")
        self.line_3 = QtGui.QFrame(self.groupBox_2)
        self.line_3.setGeometry(QtCore.QRect(17, 296, 251, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 254, 261, 16))
        self.label_9.setObjectName("label_9")
        self.line_4 = QtGui.QFrame(self.groupBox_2)
        self.line_4.setGeometry(QtCore.QRect(10, 240, 371, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(120, 290, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.botaoDeletarProducao = QtGui.QPushButton(self.centralwidget)
        self.botaoDeletarProducao.setGeometry(QtCore.QRect(170, 222, 161, 27))
        self.botaoDeletarProducao.setObjectName("botaoDeletarProducao")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 275, 591, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.botaoConverterAFparaGR = QtGui.QPushButton(self.centralwidget)
        self.botaoConverterAFparaGR.setGeometry(QtCore.QRect(10, 590, 160, 27))
        self.botaoConverterAFparaGR.setObjectName("botaoConverterAFparaGR")
        self.botaoSalvarGR = QtGui.QPushButton(self.centralwidget)
        self.botaoSalvarGR.setGeometry(QtCore.QRect(170, 250, 161, 27))
        self.botaoSalvarGR.setObjectName("botaoSalvarGR")
        self.botaSalvarAutomato = QtGui.QPushButton(self.centralwidget)
        self.botaSalvarAutomato.setGeometry(QtCore.QRect(170, 619, 160, 27))
        self.botaSalvarAutomato.setObjectName("botaSalvarAutomato")
        self.botaoCarregarGramatica = QtGui.QPushButton(self.centralwidget)
        self.botaoCarregarGramatica.setGeometry(QtCore.QRect(10, 250, 161, 27))
        self.botaoCarregarGramatica.setObjectName("botaoCarregarGramatica")
        self.botaoCarregarAutomato = QtGui.QPushButton(self.centralwidget)
        self.botaoCarregarAutomato.setGeometry(QtCore.QRect(10, 619, 161, 27))
        self.botaoCarregarAutomato.setObjectName("botaoCarregarAutomato")
        self.botaoNovoAutomato = QtGui.QPushButton(self.centralwidget)
        self.botaoNovoAutomato.setGeometry(QtCore.QRect(170, 590, 161, 27))
        self.botaoNovoAutomato.setObjectName("botaoNovoAutomato")
        self.botaoNovaGramatica = QtGui.QPushButton(self.centralwidget)
        self.botaoNovaGramatica.setGeometry(QtCore.QRect(337, 250, 271, 27))
        self.botaoNovaGramatica.setObjectName("botaoNovaGramatica")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 625, 22))
        self.menubar.setObjectName("menubar")
        self.menuAjuda = QtGui.QMenu(self.menubar)
        self.menuAjuda.setObjectName("menuAjuda")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.botaoConverterGRparaAF, QtCore.SIGNAL("clicked()"), MainWindow.converterGRparaAF)
        QtCore.QObject.connect(self.botaoAdicionarProducao, QtCore.SIGNAL("clicked()"), MainWindow.adicionarProducao)
        QtCore.QObject.connect(self.botaoGerarSentencas, QtCore.SIGNAL("clicked()"), MainWindow.gerarSentencas)
        QtCore.QObject.connect(self.botaoAdicionarEstado, QtCore.SIGNAL("clicked()"), MainWindow.adicionarEstado)
        QtCore.QObject.connect(self.botaoAdicionarAlfabeto, QtCore.SIGNAL("clicked()"), MainWindow.adicionarAlfabeto)
        QtCore.QObject.connect(self.botaoDeterminizar, QtCore.SIGNAL("clicked()"), MainWindow.determinizarAutomato)
        QtCore.QObject.connect(self.botaoMinimizar, QtCore.SIGNAL("clicked()"), MainWindow.minimizarAutomato)
        QtCore.QObject.connect(self.botaoDeletarProducao, QtCore.SIGNAL("clicked()"), MainWindow.deletarProducao)
        QtCore.QObject.connect(self.botaoDeletarEstado, QtCore.SIGNAL("clicked()"), MainWindow.deletarEstado)
        QtCore.QObject.connect(self.botaoDeletarAlfabeto, QtCore.SIGNAL("clicked()"), MainWindow.deletarAlfabeto)
        QtCore.QObject.connect(self.botaoCarregarGramatica, QtCore.SIGNAL("clicked()"), MainWindow.carregarGramatica)
        QtCore.QObject.connect(self.botaoSalvarGR, QtCore.SIGNAL("clicked()"), MainWindow.salvarGramatica)
        QtCore.QObject.connect(self.botaoConverterAFparaGR, QtCore.SIGNAL("clicked()"), MainWindow.converterAFparaGR)
        QtCore.QObject.connect(self.botaSalvarAutomato, QtCore.SIGNAL("clicked()"), MainWindow.salvarAutomato)
        QtCore.QObject.connect(self.botaoCarregarAutomato, QtCore.SIGNAL("clicked()"), MainWindow.carregarAutomato)
        QtCore.QObject.connect(self.botaoReconhecerSentenca, QtCore.SIGNAL("clicked()"), MainWindow.reconhecerSentenca)
        QtCore.QObject.connect(self.botaoNovaGramatica, QtCore.SIGNAL("clicked()"), MainWindow.novaGramatica)
        QtCore.QObject.connect(self.botaoNovoAutomato, QtCore.SIGNAL("clicked()"), MainWindow.novoAutomato)
        QtCore.QObject.connect(self.botaoConverterERparaAF, QtCore.SIGNAL("clicked()"), MainWindow.converterERparaAF)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.botaoAdicionarProducao.setText(QtGui.QApplication.translate("MainWindow", "Adicionar", None, QtGui.QApplication.UnicodeUTF8))
        self.botaoGerarSentencas.setText(QtGui.QApplication.translate("MainWindow", "Gerar", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:8.5pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Tamanho das sentenças</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Criar gramática - adicionar produções", None, QtGui.QApplication.UnicodeUTF8))
        self.botaoConverterGRparaAF.setText(QtGui.QApplication.translate("MainWindow", "Converter para Autômato", None, QtGui.QApplication.UnicodeUTF8))
        self.botaoMinimizar.setText(QtGui.QApplication.translate("MainWindow", "Minimizar Autômato", None, QtGui.QApplication.UnicodeUTF8))
        self.botaoDeterminizar.setText(QtGui.QApplication.translate("MainWindow", "Determinizar Autômato", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Configurar Autômato", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Entre com o símbolo que deseja adicionar", None, QtGui.QApplication.UnicodeUTF8))
        self.botaoAdicionarAlfabeto.setText(QtGui.QApplication.translate("MainWindow", "Adicionar Alfabeto", None, QtGui.QApplication.UnicodeUTF8))
        self.botaoAdicionarEstado.setText(QtGui.QApplication.translate("MainWindow", "Adicionar Estado", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Entre com o estado que deseja adicionar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Estado", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Alfabeto", None, QtGui.QApplication.UnicodeUTF8))
        self.botaoDeletarEstado.setText(QtGui.QApplication.translate("MainWindow", "Deletar", None, QtGui.QApplication.UnicodeUTF8))
        self.botaoDeletarAlfabeto.setText(QtGui.QApplication.translate("MainWindow", "Deletar", None, QtGui.QApplication.UnicodeUTF8))
        self.cbFinal.setText(QtGui.QApplication.translate("MainWindow", "Estado final", None, QtGui.QApplication.UnicodeUTF8))
        self.cbInicial.setText(QtGui.QApplication.translate("MainWindow", "Estado inicial", None, QtGui.QApplication.UnicodeUTF8))
        self.botaoReconhecerSentenca.setText(QtGui.QApplication.translate("MainWindow", "Reconhecer Sentença", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Entre com a sentença que deseja reconhecer", None, QtGui.QApplication.UnicodeUTF8))
        self.botaoConverterERparaAF.setText(QtGui.QApplication.translate("MainWindow", "Converter ER", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Entre com a expressão que deseja converter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Autômato", None, QtGui.QApplication.UnicodeUTF8))
        self.botaoDeletarProducao.setText(QtGui.QApplication.translate("MainWindow", "Deletar Producao", None, QtGui.QApplication.UnicodeUTF8))
        self.botaoConverterAFparaGR.setText(QtGui.QApplication.translate("MainWindow", "Converter para Gramática", None, QtGui.QApplication.UnicodeUTF8))
        self.botaoSalvarGR.setText(QtGui.QApplication.translate("MainWindow", "Salvar Gramática", None, QtGui.QApplication.UnicodeUTF8))
        self.botaSalvarAutomato.setText(QtGui.QApplication.translate("MainWindow", "Salvar Autômato", None, QtGui.QApplication.UnicodeUTF8))
        self.botaoCarregarGramatica.setText(QtGui.QApplication.translate("MainWindow", "Carregar Gramática", None, QtGui.QApplication.UnicodeUTF8))
        self.botaoCarregarAutomato.setText(QtGui.QApplication.translate("MainWindow", "Carregar Autômato", None, QtGui.QApplication.UnicodeUTF8))
        self.botaoNovoAutomato.setText(QtGui.QApplication.translate("MainWindow", "Novo Autômato", None, QtGui.QApplication.UnicodeUTF8))
        self.botaoNovaGramatica.setText(QtGui.QApplication.translate("MainWindow", "Nova Gramática", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAjuda.setTitle(QtGui.QApplication.translate("MainWindow", "Ajuda", None, QtGui.QApplication.UnicodeUTF8))

